package xyz.mlserver.mod.mlserverdbdmod;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.ScaledResolution;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.RenderHelper;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.client.FMLConfigGuiFactory;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;
import net.minecraftforge.fml.relauncher.Side;
import org.apache.logging.log4j.Logger;
import xyz.mlserver.mod.mlserverdbdmod.listeners.ForgeConfigChangeListener;
import xyz.mlserver.mod.mlserverdbdmod.listeners.ForgeGuiOpenListener;
import xyz.mlserver.mod.mlserverdbdmod.listeners.ForgeInventoryItemRendererListener;


@Mod(
        modid = MLServerDbDMod.MODID,
        name = MLServerDbDMod.NAME,
        version = MLServerDbDMod.VERSION,
        guiFactory = "xyz.mlserver.mod.mlserverdbdmod.utils.GuiFactoryMLServerDbDMod"
)
public class MLServerDbDMod {
    public static final String MODID = "mlserverdbdmod";
    public static final String NAME = "MLServer DbD Mod";
    public static final String VERSION = "1.0.0";

    private static Logger logger;

    public static Loader loader;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();
        loadInfo(event.getModMetadata());
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        // some example code
        ForgeInventoryItemRendererListener listener = new ForgeInventoryItemRendererListener();
        FMLCommonHandler.instance().bus().register(new ForgeConfigChangeListener());
        FMLCommonHandler.instance().bus().register(new ForgeGuiOpenListener());

        loader = Loader.instance();
    }

    public static void loadInfo(ModMetadata meta) {
        meta.modId = MLServerDbDMod.MODID;
        meta.name = MLServerDbDMod.NAME;
        meta.description = "Mod checker for MonsterLifeServer.";
        meta.version = MLServerDbDMod.VERSION ;
        meta.url = "https://wiki.mlserver.xyz/?p=20";
        meta.authorList.add("Monster2408");
        meta.credits = "";
        meta.logoFile = "assets/mlserverdbdmod/logo.png";
        meta.autogenerated = false;
    }
}
